# Generated by Django 6.0.3 on 2026-04-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_order_address_order_name_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
