# Generated by Django 6.0.3 on 2026-04-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_like_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
