# Generated by Django 6.0.3 on 2026-05-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='send_count',
            field=models.IntegerField(default=0),
        ),
    ]
