# Generated by Django 6.0.3 on 2026-05-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_otp_last_sent_at_otp_send_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='type',
            field=models.CharField(default='register', max_length=20),
        ),
    ]
