# Generated by Django 6.0.3 on 2026-05-04 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_otp_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='type',
            new_name='otp_type',
        ),
    ]
