# Generated by Django 6.0.3 on 2026-05-06 11:46

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_product_is_active_product_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.product_image_path),
        ),
    ]
