# Generated by Django 6.0.3 on 2026-05-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
