function Products() {
  return [
    { id: 1, name: "Veg Burger", price: 120, category: "veg", rating: "4.9", image: "/images/veg_burger.png" },
    { id: 2, name: "Chicken Pizza", price: 250, category: "non-veg", rating: "4.8", image: "/images/chicken_pizza.png" },
    { id: 3, name: "Jigarthanda", price: 100, category: "drinks", rating: "4.6", image: "/images/jigarthanda.png" },
    { id: 4, name: "Chicken Briyani", price: 120, category: "non-veg", rating: "4.5", image: "/src/assets/images/chicken_briyani.png"},
    { id: 5, name: "Chicken Rice", price: 120, category: "non-veg", rating: "4.7", image: "/images/Chicken_Rice.png"},
    { id: 6, name: "Mutton Briyani", price: 220, category: "non-veg", rating: "4.8", image: "/src/assets/images/mutton_briyani.png"},
    { id: 7, name: "Beef Briyani", price: 180, category: "non-veg", rating: "4.7", image: "/src/assets/images/beef_briyani.png"},
    { id: 8, name: "Egg Briyani", price: 100, category: "non-veg", rating: "4.3", image: "/src/assets/images/egg_briyani.png"},
    { id: 9, name: "Empty Briyani", price: 90, category: "non-veg", rating: "4.2", image: "/src/assets/images/empty_briyani.png"},
    { id: 10, name: "Grill", price: 360, category: "non-veg", rating: "4.7", image: "/images/grill.png"},
    { id: 11, name: "Tandoori", price: 350, category: "non-veg", rating: "4.6", image: "/src/assets/images/tandoori.png"},
    { id: 12, name: "Swarma", price: 99, category: "non-veg", rating: "4.8", image: "/src/assets/images/swarma.png"},
    { id: 13, name: "Idly", price: 15, category: "veg", rating: "4.6", image: "/src/assets/images/idly.png"},
    { id: 14, name: "Plain Dosa", price: 50, category: "veg", rating: "4.5", image: "/src/assets/images/plain_dosai.png"},
    { id: 15, name: "Idiyappam", price: 15, category: "veg", rating: "4.4", image: "/src/assets/images/idiyappam.png"},
    { id: 16, name: "Poori", price: 25, category: "veg", rating: "4.5", image: "/src/assets/images/poori.png"},
    { id: 17, name: "Pongal", price: 40, category: "veg", rating: "4.5", image: "/src/assets/images/pongal.png"},
    { id: 18, name: "Vada", price: 15, category: "side-dish", rating: "4.6", image: "/src/assets/images/vadai.png"},
    { id: 19, name: "Samosa", price: 20, category: "side-dish", rating: "4.5", image: "/src/assets/images/samosa.png"},
    { id: 20, name: "Bonda", price: 15, category: "side-dish", rating: "4.2", image: "/src/assets/images/bonda.png"},
    { id: 21, name: "Veg Fried Rice", price: 90, category: "veg", rating: "4.1", image: "/src/assets/images/veg_rice.png"},
    { id: 22, name: "Gopi Fried Rice", price: 100, category: "veg", rating: "4.4", image: "/src/assets/images/gopi_rice.png"},
    { id: 23, name: "Paneer Fried Rice", price: 110, category: "veg", rating: "4.3", image: "/src/assets/images/paneer_rice.png"},
    { id: 24, name: "Mushroom Rice", price: 110, category: "veg", rating: "4.6", image: "/src/assets/images/mushroom_rice.png"},
    { id: 25, name: "Brinji", price: 60, category: "veg", rating: "4.4", image: "/src/assets/images/brinji.png"},
    { id: 26, name: "Sambar Satham", price: 50, category: "veg", rating: "4.1", image: "/src/assets/images/sambar_rice.png"},
    { id: 27, name: "Meals", price: 120, category: "veg", rating: "4.7", image: "/src/assets/images/meals.png"},
    { id: 28, name: "Curd Rice", price: 50, category: "veg", rating: "4.5", image: "/src/assets/images/curd_rice.png"},
    { id: 29, name: "Lemon Rice", price: 50, category: "veg", rating: "4.4", image: "/src/assets/images/lemon_rice.png"},
    { id: 30, name: "Chicken Noodles", price: 150, category: "non-veg", rating: "4.7", image: "/src/assets/images/chicken_noodles.png"},
    { id: 31, name: "Mushroom Noodles", price: 110, category: "veg", rating: "4.5", image: "/src/assets/images/mushroom_noodles.png"},
    { id: 32, name: "Gopi Noodles", price: 110, category: "veg", rating: "4.6", image: "/src/assets/images/gopi_noodles.png"},
    { id: 33, name: "Paneer Noodles", price: 120, category: "veg", rating: "4.7", image: "/src/assets/images/paneer_noodles.png"},
    { id: 34, name: "Bajji", price: 30, category: "side-dish", rating: "4.9", image: "/src/assets/images/bajji.png"},
    { id: 35, name: "Chappathi", price: 30, category: "veg", rating: "4.5", image: "/src/assets/images/chappathi.png"},
    { id: 36, name: "Parotta", price: 30, category: "veg", rating: "4.5", image: "/src/assets/images/parotta.png"},
    { id: 37, name: "Chicken Kothu parotta", price: 180, category: "non-veg", rating: "4.8", image: "/src/assets/images/chicken_kothu_parotta.png"},
    { id: 38, name: "Veg Kothu Parotta", price: 100, category: "veg", rating: "4.4", image: "/src/assets/images/veg_kothu_parotta.png"},
    { id: 39, name: "Chilly Parotta", price: 150, category: "non-veg", rating: "4.9", image: "/src/assets/images/chilly_parotta.png"},
    { id: 40, name: "Nool Parotta", price: 120, category: "veg", rating: "4.7", image: "/src/assets/images/nool_parotta.png"},
    { id: 41, name: "Ghee Roast", price: 80, category: "veg", rating: "4.7", image: "/src/assets/images/ghee_roast.png"},
    { id: 42, name: "Chicken Dosa", price: 150, category: "non-veg", rating: "4.9", image: "/src/assets/images/chicken_dosa.png"},
    { id: 43, name: "Mushroom Masala Dosa", price: 120, category: "veg", rating: "4.7", image: "/src/assets/images/mushroom_dosai.png"},
    { id: 44, name: "Gopi Masala Dosa", price: 110, category: "veg", rating: "4.6", image: "/src/assets/images/gopi_masala_dosa.png"},
    { id: 45, name: "Paneer Masala Dosa", price: 120, category: "veg", rating: "4.6", image: "/src/assets/images/paneer_masala_dosa.png"},
    { id: 46, name: "Masala Dosa", price: 70, category: "veg", rating: "4.5", image: "/src/assets/images/masala_dosa.png"},
    { id: 47, name: "Kal Dosa", price: 40, category: "veg", rating: "4.5", image: "/src/assets/images/kal_dosa.png"},
    { id: 48, name: "Onion Uthappam", price: 70, category: "veg", rating: "4.7", image: "/src/assets/images/onion_uthappam.png"},
    { id: 49, name: "Boiled Egg", price: 15, category: "side-dish", rating: "4.5", image: "/src/assets/images/boiled_egg.png"},
    { id: 50, name: "Omelette", price: 30, category: "side-dish", rating: "4.5", image: "/src/assets/images/omelette.png"},
    { id: 51, name: "Kalaki", price: 30, category: "side-dish", rating: "4.7", image: "/src/assets/images/kalaki.png"},
    { id: 52, name: "Chilli Chicken", price: 120, category: "non-veg", rating: "4.6", image: "/src/assets/images/chilly_chicken.png"},
    { id: 53, name: "Chicken 65", price: 110, category: "non-veg", rating: "4.4", image: "/src/assets/images/chicken_65.png"},
    { id: 54, name: "Gopi Manjurian", price: 70, category: "veg", rating: "4.8", image: "/src/assets/images/gopi_manjuriyan.png"},
    { id: 55, name: "Barbeque Chicken", price: 360, category: "non-veg", rating: "4.6", image: "/src/assets/images/barbeque.png"},
    { id: 56, name: "Paneer Manjurian", price: 90, category: "veg", rating: "4.3", image: "/src/assets/images/paneer_manjurian.png"},
    { id: 57, name: "Rava Dosa", price: 100, category: "veg", rating: "4.7", image: "/src/assets/images/rava_dosa.png"},
    { id: 58, name: "Gopi Chilli", price: 110, category: "veg", rating: "4.2", image: "/src/assets/images/gopi_chilly.png"},
    { id: 59, name: "Sprite", price: 20, category: "drinks", rating: "4.1", image: "/src/assets/images/sprite.png"},
    { id: 60, name: "Thums Up", price: 30, category: "drinks", rating: "4.2", image: "/src/assets/images/thums_up.png"},
    { id: 61, name: "Coke", price: 30, category: "drinks", rating: "4.4", image: "/src/assets/images/coca_cola.png"},
    { id: 62, name: "Paneer Chilli", price: 120, category: "veg", rating: "4.4", image: "/src/assets/images/paneer_chilli.png"},
    { id: 63, name: "Goli Soda", price: 40, category: "drinks", rating: "4.9", image: "/src/assets/images/goli_soda.png"},
    { id: 64, name: "Lemon Juice", price: 30, category: "drinks", rating: "4.7", image: "/src/assets/images/lemon_juice.png"},
    { id: 65, name: "Egg Noodles", price: 110, category: "non-veg", rating: "4.8", image: "/src/assets/images/egg_noodles.png"},
    { id: 66, name: "Egg Fried Rice", price: 120, category: "non-veg", rating: "4.7", image: "/src/assets/images/egg_rice.png"},
    { id: 67, name: "Butter Chicken", price: 160, category: "non-veg", rating: "4.8", image: "/src/assets/images/butter_chicken.png"},
    { id: 68, name: "Naan", price: 50, category: "veg", rating: "4.5", image: "/src/assets/images/naan.png"},
    { id: 69, name: "Butter Naan", price: 70, category: "veg", rating: "4.5", image: "/src/assets/images/butter_naan.png"},
    { id: 70, name: "Chicken Stuffed", price: 120, category: "non-veg", rating: "4.9", image: "/src/assets/images/chicken_stuffed.png"},
    { id: 71, name: "Garlic Dosa", price: 110, category: "veg", rating: "4.8", image: "/src/assets/images/garlic_dosa.png"},
    { id: 72, name: "Chicken Lolipop", price: 120, category: "non-veg", rating: "4.8", image: "/src/assets/images/chicken_lolipop.png"},
    { id: 73, name: "Bun Parotta", price: 50, category: "non-veg", rating: "4.7", image: "/src/assets/images/bun_parotta.png"},
    { id: 74, name: "Kizhi Parotta", price: 100, category: "non-veg", rating: "4.7", image: "/src/assets/images/kizhi_parotta.png"},
    { id: 75, name: "Veechu Parotta", price: 90, category: "non-veg", rating: "4.6", image: "/src/assets/images/veechu_parotta.png"},
    { id: 76, name: "Coin Parotta", price: 60, category: "non-veg", rating: "4.7", image: "/src/assets/images/coin_parotta.png"},
  ];
}
