function Products() {
  return [
    { id: 1, name: "Veg Burger", price: 120, category: "veg", rating: 4.9, image: "" },
    { id: 2, name: "Chicken Pizza", price: 250, category: "non-veg", rating: 4.8, image: "" },
    { id: 3, name: "Jigarthanda", price: 100, category: "drinks", rating: 4.6, image: "" },
    { id: 4, name: "Chicken Briyani", price: 120, category: "non-veg", rating: 4.5, image: "" },
    { id: 5, name: "Chicken Rice", price: 120, category: "non-veg", rating: 4.7, image: "" },
    { id: 6, name: "Mutton Briyani", price: 220, category: "non-veg", rating: 4.8, image: "" },
    { id: 7, name: "Beef Briyani", price: 180, category: "non-veg", rating: 4.7, image: "" },
    { id: 8, name: "Egg Briyani", price: 100, category: "non-veg", rating: 4.3, image: "" },
    { id: 9, name: "Empty Briyani", price: 90, category: "non-veg", rating: 4.2, image: "" },
    { id: 10, name: "Grill", price: 360, category: "non-veg", rating: 4.7, image: "" },

    { id: 11, name: "Tandoori", price: 350, category: "non-veg", rating: 4.6, image: "" },
    { id: 12, name: "Swarma", price: 99, category: "non-veg", rating: 4.8, image: "" },
    { id: 13, name: "Idly", price: 15, category: "veg", rating: 4.6, image: "" },
    { id: 14, name: "Plain Dosa", price: 50, category: "veg", rating: 4.5, image: "" },
    { id: 15, name: "Idiyappam", price: 15, category: "veg", rating: 4.4, image: "" },
    { id: 16, name: "Poori", price: 25, category: "veg", rating: 4.5, image: "" },
    { id: 17, name: "Pongal", price: 40, category: "veg", rating: 4.5, image: "" },
    { id: 18, name: "Vada", price: 15, category: "side-dish", rating: 4.6, image: "" },
    { id: 19, name: "Samosa", price: 20, category: "side-dish", rating: 4.5, image: "" },
    { id: 20, name: "Bonda", price: 15, category: "side-dish", rating: 4.2, image: "" },

    { id: 21, name: "Veg Fried Rice", price: 90, category: "veg", rating: 4.1, image: "" },
    { id: 22, name: "Gopi Fried Rice", price: 100, category: "veg", rating: 4.4, image: "" },
    { id: 23, name: "Paneer Fried Rice", price: 110, category: "veg", rating: 4.3, image: "" },
    { id: 24, name: "Mushroom Rice", price: 110, category: "veg", rating: 4.6, image: "" },
    { id: 25, name: "Brinji", price: 60, category: "veg", rating: 4.4, image: "" },
    { id: 26, name: "Sambar Satham", price: 50, category: "veg", rating: 4.1, image: "" },
    { id: 27, name: "Meals", price: 120, category: "veg", rating: 4.7, image: "" },
    { id: 28, name: "Curd Rice", price: 50, category: "veg", rating: 4.5, image: "" },
    { id: 29, name: "Lemon Rice", price: 50, category: "veg", rating: 4.4, image: "" },
    { id: 30, name: "Chicken Noodles", price: 150, category: "non-veg", rating: 4.7, image: "" },

    { id: 31, name: "Mushroom Noodles", price: 110, category: "veg", rating: 4.5, image: "" },
    { id: 32, name: "Gopi Noodles", price: 110, category: "veg", rating: 4.6, image: "" },
    { id: 33, name: "Paneer Noodles", price: 120, category: "veg", rating: 4.7, image: "" },
    { id: 34, name: "Bajji", price: 30, category: "side-dish", rating: 4.9, image: "" },
    { id: 35, name: "Chappathi", price: 30, category: "veg", rating: 4.5, image: "" },
    { id: 36, name: "Parotta", price: 30, category: "veg", rating: 4.5, image: "" },
    { id: 37, name: "Chicken Kothu Parotta", price: 180, category: "non-veg", rating: 4.8, image: "" },
    { id: 38, name: "Veg Kothu Parotta", price: 100, category: "veg", rating: 4.4, image: "" },
    { id: 39, name: "Chilly Parotta", price: 150, category: "non-veg", rating: 4.9, image: "" },
    { id: 40, name: "Nool Parotta", price: 120, category: "veg", rating: 4.7, image: "" },

    { id: 41, name: "Ghee Roast", price: 80, category: "veg", rating: 4.7, image: "" },
    { id: 42, name: "Chicken Dosa", price: 150, category: "non-veg", rating: 4.9, image: "" },
    { id: 43, name: "Mushroom Masala Dosa", price: 120, category: "veg", rating: 4.7, image: "" },
    { id: 44, name: "Gopi Masala Dosa", price: 110, category: "veg", rating: 4.6, image: "" },
    { id: 45, name: "Paneer Masala Dosa", price: 120, category: "veg", rating: 4.6, image: "" },
    { id: 46, name: "Masala Dosa", price: 70, category: "veg", rating: 4.5, image: "" },
    { id: 47, name: "Kal Dosa", price: 40, category: "veg", rating: 4.5, image: "" },
    { id: 48, name: "Onion Uthappam", price: 70, category: "veg", rating: 4.7, image: "" },
    { id: 49, name: "Boiled Egg", price: 15, category: "side-dish", rating: 4.5, image: "" },
    { id: 50, name: "Omelette", price: 30, category: "side-dish", rating: 4.5, image: "" },

    { id: 51, name: "Kalaki", price: 30, category: "side-dish", rating: 4.7, image: "" },
    { id: 52, name: "Chilli Chicken", price: 120, category: "non-veg", rating: 4.6, image: "" },
    { id: 53, name: "Chicken 65", price: 110, category: "non-veg", rating: 4.4, image: "" },
    { id: 54, name: "Gopi Manjurian", price: 70, category: "veg", rating: 4.8, image: "" },
    { id: 55, name: "Barbeque Chicken", price: 360, category: "non-veg", rating: 4.6, image: "" },
    { id: 56, name: "Paneer Manjurian", price: 90, category: "veg", rating: 4.3, image: "" },
    { id: 57, name: "Rava Dosa", price: 100, category: "veg", rating: 4.7, image: "" },
    { id: 58, name: "Gopi Chilli", price: 110, category: "veg", rating: 4.2, image: "" },
    { id: 59, name: "Sprite", price: 20, category: "drinks", rating: 4.1, image: "" },
    { id: 60, name: "Thums Up", price: 30, category: "drinks", rating: 4.2, image: "" },

    { id: 61, name: "Coke", price: 30, category: "drinks", rating: 4.4, image: "" },
    { id: 62, name: "Paneer Chilli", price: 120, category: "veg", rating: 4.4, image: "" },
    { id: 63, name: "Goli Soda", price: 40, category: "drinks", rating: 4.9, image: "" },
    { id: 64, name: "Lemon Juice", price: 30, category: "drinks", rating: 4.7, image: "" },
    { id: 65, name: "Egg Noodles", price: 110, category: "non-veg", rating: 4.8, image: "" },
    { id: 66, name: "Egg Fried Rice", price: 120, category: "non-veg", rating: 4.7, image: "" },
    { id: 67, name: "Butter Chicken", price: 160, category: "non-veg", rating: 4.8, image: "" },
    { id: 68, name: "Naan", price: 50, category: "veg", rating: 4.5, image: "" },
    { id: 69, name: "Butter Naan", price: 70, category: "veg", rating: 4.5, image: "" },
    { id: 70, name: "Chicken Stuffed", price: 120, category: "non-veg", rating: 4.9, image: "" },

    { id: 71, name: "Garlic Dosa", price: 110, category: "veg", rating: 4.8, image: "" },
    { id: 72, name: "Chicken Lolipop", price: 120, category: "non-veg", rating: 4.8, image: "" },
    { id: 73, name: "Bun Parotta", price: 50, category: "non-veg", rating: 4.7, image: "" },
    { id: 74, name: "Kizhi Parotta", price: 100, category: "non-veg", rating: 4.7, image: "" },
    { id: 75, name: "Veechu Parotta", price: 90, category: "non-veg", rating: 4.6, image: "" },
    { id: 76, name: "Coin Parotta", price: 60, category: "non-veg", rating: 4.7, image: "" },
  ];
}

export default Products;